language: node_js
node_js:
  - "0.10"
services:
  - mongodb
secure: "fyTOSWoSmtpLDu6gjj5bF5y+qfUNYo3ophvGD+U+B2sfLE0gubg4TcI2D86qxf/tQo96uCIlU71shy43VEVv/v9hXRPWcydxf8r7kmXTbW9Amf15AYB3VweM+ils+aFKrxj4ScKIW6g113N9J2wdyB8jX9WbTVHwG9GckkRsxpFqndZIGlbaChbcoJTshVp5ntWLovyp58+X32LP922YAh/guQ/fU6w2vaAZYeeGChdFsCZdWwnycmMkaHYdo7DjWlaJQmvD/opRZGGkG+en+6Oi5PK3J4uOH9rLMl8AG0jdAaVcS6N/yseGwqF048KpeHGQTPf0ZXUz54TCHKR88SBdhGN6Qi9iXrTGfOm3nJyxOp5z19lpqsocVVKmgZZIq404TkEsXC2qitrUA7LvN38HHQYaaOzAT4XEwhWV6yiW2wIy7y+cuH/ObDawNqs8mEiABnFSO+8EUTeuPVT/5PTRKXQ0htIVkrsjGK1i+M/+gsuXUxX/dkUiWtWaSJUKMEK0tBVeipKC1aNcIjQYrecSA19xQ53okq0oUT7baV5JfQY6K23fu0YNsu3inxeMvsVzV6P/RDHZPrHJRd79dv9I06WVzxIlNahprF4va9xEq7gkfHzqMJVYeHLn7p8mhbVNGkVgv596qenI9bxAQIzf/8Ug0BInjarQXbHceZg="
