language: node_js
node_js:
- '0.10'
services:
- mongodb
env:
  global:
    secure: OEjk76DNHVRiR59s4DVBGajW6PJJRuez78H17wtjlLdSqkSIk+x0WfFZ9aW0LpSz37udXCfNfJWr8dIhQL6kgJL6mZk5sauMSvnPuAv/OHx2Im0GOa9H8eZykv1rQf5vJoD1EmIH3a584NwAXBunQdIjnkVLfwh5RNSra3pNtjF80RxHoutNMnQLDpBbcP+WDhswbULJOVdX3pkKaRaYElG/RnQhNRr8eUMYt1dGuhoqiUD29PnODe6nmkZvlF7mvxYQgzUGvddHm32HUME0ehjnqfr0opFxi7x0deGsbKYuf7MgEd+1AKElEIf49sb1tNEBefQp3R6z0YmLgsngGH/dx/RiXs9LZx44H38gg35j3bzAtqknoL5f6yUneufMM9SuAj9yu3BsT1B3qQmHq+nvzB0CUX2cbKadJ5xAvGnPr5cszMzbFk3kYqlkLsJjwV9wVR0kuAjA2kC4qS6YUOXcFf+IItGZqqyfRai55gmnRgAK1YdEhbFnQr7yUXMz/nzA8n7oUsP6AHvzhyB2Qe4L5zRTZjiWFQOb1A2if75ah5hNxNZxRWX8Zm5+Sj8wJ2M56z6mKhnYIAziQGD3YEUeN2zWb1QHF3EED3VRbbWJymET2PDxVnQAxWDv+s8BDcd8RZqMrxXmBnC+3LSiAtkXUhQyRpra/93VwLaAO+Y=
